// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4TgpWViBLbzlG0lVQyH54RVEeM_wX2dQ',
    appId: '1:595066935926:web:0a18b96cc3222e0a655d57',
    messagingSenderId: '595066935926',
    projectId: 'shopapp-b2dd8',
    authDomain: 'shopapp-b2dd8.firebaseapp.com',
    storageBucket: 'shopapp-b2dd8.appspot.com',
    measurementId: 'G-ZEMCT190E5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjjsTl7WRcUlWpBIomBQcEv2DXOOtrgI8',
    appId: '1:595066935926:android:4be28882b2a0fe63655d57',
    messagingSenderId: '595066935926',
    projectId: 'shopapp-b2dd8',
    storageBucket: 'shopapp-b2dd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYjWP7-1aGrQfWxJstDclLdZGLk-5HV-4',
    appId: '1:595066935926:ios:784bddbe4dac2541655d57',
    messagingSenderId: '595066935926',
    projectId: 'shopapp-b2dd8',
    storageBucket: 'shopapp-b2dd8.appspot.com',
    iosBundleId: 'com.example.doctorAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYjWP7-1aGrQfWxJstDclLdZGLk-5HV-4',
    appId: '1:595066935926:ios:784bddbe4dac2541655d57',
    messagingSenderId: '595066935926',
    projectId: 'shopapp-b2dd8',
    storageBucket: 'shopapp-b2dd8.appspot.com',
    iosBundleId: 'com.example.doctorAppUi',
  );
}
